export { default as Navbar } from './Navbar';
export { default as Hero } from './Hero';
export { default as Problem } from './Problem';
export { default as HowItWorks } from './HowItWorks';
export { default as Features } from './Features';
export { default as Stats } from './Stats';
export { default as Testimonials } from './Testimonials';
export { default as FinalCTA } from './FinalCTA';
export { default as Footer } from './Footer';
